# Generated by Django 4.2.8 on 2023-12-19 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='code_verification',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='код верификации'),
        ),
    ]
