# Generated by Django 4.2.8 on 2023-12-19 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_code_verification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='code_verification',
        ),
        migrations.AddField(
            model_name='user',
            name='code',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Код верификации'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Статус'),
        ),
    ]
